---
title: "mid_2"
author: "b06208016楊鎧綾"
date: "November 27, 2018"
output: html_document
---
#轉換
```{r}
#qt-知道面積求t-score
qt(0.01, df = 10, lower.tail = FALSE)
qt(0.01, df = 200, lower.tail = FALSE)
#qnorm-知道面積求z-score
qnorm(0.01, lower.tail = FALSE)

#pt-知道t-score求面積
pt(2, df = 10, lower.tail = FALSE)
pt(2, df = 200, lower.tail = FALSE)
#pnorm-知道z-score求面積
pnorm(2, lower.tail = FALSE)
```

#各種檢定
```{r}
#已知sample算信賴區間
prop.test(x=0.3*439,n=439,alternative = "two.sided",conf.level = 0.95)
prop.test(x=c(85,24),n=c(1105,1379),alternative = "two.sided",conf.level = 0.95)
#
x=c(1,23,6,5,8,9,75,35)
t.test(x, alternative = "two.sided", conf.level=0.95)
#
exer_t<-c(62,72,60,63,75,64,60,52,64,80,68,64)
exer_f<-c(72,84,66,72,62,84,76,60)
t.test(exer_t,exer_f,alternative="two.sided",paired = F,var.equal = F,conf.level = 0.95)

#看p-value(注意信心水準)
##hypothesis_one proportion 
prop.test(x = 103, n = 215, 
          p = 0.5, alternative = "two.sided", 
          conf.level = 0.95, correct = F)
##hypothesis_two proportions
prop.test(x = c(123, 100), n = c(300,250), 
          alternative = "two.sided", 
          conf.level = 0.99, correct = F)
#
bean_d=c(4,4,5,1,-2,0,2,4,-3,0,0,0,-2,2,1)
t.test(bean_d,alternative="greater",paired = F,var.equal = F,conf.level = 0.95)
```

#ch1 已知母體模擬樣本與理論相比

```{r}
#sampling one time(function is for making one mean)
#機率為p的時候抽n個，回傳成功的機率
bino.x=function(n,p){
  pp=p*100
  samp=sample(1:100,n,replace=T)#隨機抽n個
  response=c()
  #確認哪些符合條件
  for (i in 1:length(samp)){
    if (samp[i]<=pp){
      response[i]=1
    }else{
      response[i]=0
    }
  }
  p=sum(response)/n
  return(p)#回傳符合的比例
}

#sampling multiple times
#return 1000 phat
simu.phat=c()
for (j in 1:1000){
  x=bino.x(400,0.05)
  simu.phat[j]=x
}
```
```{r}
#計算模擬的phat的mean和sd
simu.mean=mean(simu.phat)
simu.sd=sd(simu.phat)
#計算理論的phat的mean和sd
n=400
p=0.05
theo.mean=p
theo.sd=sqrt(p*(1-p)/n)
```
```{r}
#draw sample distribution
hist(simu.phat,probability = T,breaks = 20,main="sample distribution of phat by sampling",xlab="phat",col = "gold",border="white",ylim=c(0,40))
#加上理論的部分
curve(dnorm(x,theo.mean,theo.sd),add=T,col="navy",lwd=2)
```

```{r}
#sample one time
#每次有n個觀測者
norm.x=function(n,mu,sigma){
  samp=rnorm(n,mu,sigma)
  xbar=mean(samp)
  return(xbar)
}
#sample multiple times
simu.xbar=c()
for (j in 1:1000){
  x=norm.x(365,80,50)
  simu.xbar[j]=x
}
#計算模擬的xbar的mean和sd
simu.mean=mean(simu.xbar)
simu.sd=sd(simu.xbar)
#計算理論的xbar的mean和sd
mu=80
sigma=50
n=365
theo.mean=mu;theo.mean
theo.sd=sigma/sqrt(n);theo.sd

#draw sample distribution
hist(simu.xbar,probability = T,breaks = 20,main="sample distribution of xbar by sampling",xlab="xbar",col = "gold",border="white")
#加上理論的部分
curve(dnorm(x,80,2.61712),add=T,col="navy",lwd=2)
```
##polygon
```{r}
x=seq(-0.2,0.2,length.out=1000)
y=dnorm(x,0.03,0.03)
curve(dnorm(x,0.03,0.03),lwd=2,main="sampling distribution of phat1-phat2",xlim=c(-0.2,0.2),xlab="sample proportations",ylab="density")
## Add the polygon
region.x = x[x<=0]
region.y = y[x<=0]
region.x2 = c(region.x,0)
region.y2 = c(region.y, 0)
polygon(region.x2, region.y2, col = "red")
```

#ch2 confidence interval

##已知樣本比例模擬抽樣多次母體信賴區間(每次結果不同)
```{r}
Prop_CI = function(n, p, confd) {
 
  all.phat = c()
  for (i in 1:10000) {
    phat = sum(sample(c(0,1), n, replace = T, prob = c(1-p,p)))/n
    all.phat[i] = phat
  }
  
  all.phat = sort(all.phat)
  
  low.per = ceiling(((1-confd)/2)*10000)
  low.vlue = all.phat[low.per]
  high.per = ceiling((1-((1-confd)/2))*10000)
  high.vlue = all.phat[high.per]
  
  results = c(paste((1-confd)/2*100,"%"), paste((1-((1-confd)/2))*100,"%"), low.vlue, high.vlue)
  
  mean.p = mean(all.phat)
  sd.p = sd(all.phat)
  
  CI = list(CI = matrix(results, nrow = 2, byrow = T), mean = mean.p, sd = sd.p )
  
  return(CI)
}

Prop_CI(883,0.68,0.95)
```

##手動計算信賴區間
```{r}
n = 883
p = 0.68

z = qnorm((1-0.95)/2, lower.tail = F)
se = sqrt(p*(1-p)/n)

high.c = p + z*se; high.c
low.c = p - z*se; low.c
```

##已知母體比例模擬多次每次抽樣計算出的信賴區間(每次結果不同)
```{r}
Sim_CI<-function(n,mu,sd,m,conf.level){
  
  prob<-(1-conf.level)/2
  t.value=qt(prob,df=n-1,lower.tail=FALSE)
  
  mean.x=c()
  se.x=c()
  
  CI.half=c()
  CI.Up=c()
  CI.Lower=c()
  Check=c()
  
  #Mumeanltiple sampling
  for (i in 1:m){
    
    #one sampling
    x<-rnorm(n,mean=mu,sd=sd)
    mean.x[i]<-mean(x)
    se.x[i]<-sd(x)/sqrt(n)
    
    #calculate one confidence interval
    CI.half[i]<-t.value*se.x[i]
    CI.Up[i]<-mean.x[i]+CI.half[i]
    CI.Lower[i]<-mean.x[i]-CI.half[i]
    if(CI.Up[i]>mu & CI.Lower[i]<mu) Check[i]<-1 else Check[i]<-0
  }
  
  plot(c(CI.Up,CI.Lower),type="n",pch=19,xlim=c(1,m),xlab="Trial",ylab=expression(mu))  #n=甚麼都不畫
  abline(h=mu,col="blue")
  
  #check weather each confidence interval captures the population mean (mu)
  for (i in 1:m){
    if (Check[i]==1){
      points(i, mean.x[i], col="green", pch=10)
      points(i, CI.Up[i], col="green", pch=20)
      points(i, CI.Lower[i], col="green", pch=20)
      lines(c(i,i),c(CI.Lower[i],CI.Up[i]), col="green", pch=19)
      
    }else{
      points(i, mean.x[i], col="red", pch=10)
      points(i, CI.Up[i], col="red", pch=20)
      points(i, CI.Lower[i], col="red", pch=20)
      lines(c(i,i),c(CI.Lower[i],CI.Up[i]), col="red", pch=19)
    }
  }
  

  title(expression(paste("Simulating confidence interval for",mu)))
  
  legend("bottomright",cex=0.6,bty = "n",ncol = 2,
         c(expression(paste(mu,"Captured")),expression(paste(mu,"Not Captured"))),
         fill = c("green","red"))
  
  No.Captured = m-sum(Check)
  RESULT = list(Trial=m, Sample.Size=n,
                Population.mean=mu, Population.sd=sd,
                Confidence=conf.level,
                No.Captured=No.Captured)
  
  return(RESULT)
}

Sim_CI(n=30, m=100, mu=50, sd=5, conf.level=0.95)

```


